language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-27.0.1
    - android-27
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  email: false

before_install:
 - chmod +x gradlew

script: ./gradlew clean
