language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services

notifications:
  email: false

before_install:
 - chmod +x gradlew

script: ./gradlew clean
